# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Link to your container registry. You will launch it in Yandex Cloud.
  repository: cr.yandex/crpqcenorrrmvqsjd19f/dds_service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2025-11-29-r1"

containerPort: 5000

config:
  KAFKA_HOST:"rc1a-ehv0jqtvitmfbegr.mdb.yandexcloud.net"
  KAFKA_PORT:"9091"
  KAFKA_CONSUMER_USERNAME:"producer_consumer"
  KAFKA_CONSUMER_PASSWORD:"pass"
  KAFKA_CONSUMER_GROUP:"group_1"
  KAFKA_STG_SERVICE_ORDERS_TOPIC:"stg-service-orders"
  KAFKA_DDS_SERVICE_ORDERS_TOPIC:"dds-service-orders"

  PG_WAREHOUSE_HOST:"rc1b-9d8ddg17omhti3pe.mdb.yandexcloud.net"
  PG_WAREHOUSE_PORT:6432
  PG_WAREHOUSE_DBNAME:"sprint9dwh"
  PG_WAREHOUSE_USER:"mvzhyp"
  PG_WAREHOUSE_PASSWORD:"pass"

  REDIS_HOST:"c-c9qeovjcskn4nlhnenj1.rw.mdb.yandexcloud.net"
  REDIS_PORT:6380
  REDIS_PASSWORD:"pass"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
